app_name: "album-store"
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

database:
  host: localhost
  port: 5435
  user: albumstoreuser
  password: albumstore
  dbname: album-store
  sslmode: disable
