app_name: "album-store"
app_version: "0.0.1"

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

database:
  host: localhost
  port: 5432
  user: albumstoreuser
  password: albumstore
  dbname: album-store
  sslmode: disable
uptrace:
  dsn: "http://project2_secret_token@localhost:14317/2"
  endpoint: "http://localhost:14317"
