name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4


      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx -y semantic-release
